### ISSUE TITLE
ebay kleinanzeigen fails with undefined error

### ISSUE THREAD

**Issue by chbndrhnns** [adriankumpf/findmeaflat#4]
When I have a search for ebay kleinanzeigen, the scraper fails with 

```
TypeError: Cannot read property 'join' of undefined
    at Object.isOneOf (/app/lib/utils.js:2:42)
    at applyBlacklist (/app/lib/sources/kleinanzeigen.js:13:32)
    at Array.filter (<anonymous>)
    at FlatFinder.run (/app/lib/flatfinder.js:21:8)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

If I add this lines to `utils.js` it seems to work:

```
function isOneOf(word, arr) {
  if (arr === undefined) {
    return true
  }
```

**Comment by chbndrhnns** [comment]
Thanks, it works now here!
